language: c

sudo: false

compiler:
  - gcc
  - clang

cache:
  directories:
    - $HOME/local
    - $HOME/.luarocks
    - $HOME/.python
    - $HOME/.ccache

addons:
  apt:
    sources:
    packages:
      - lua5.1
      - liblua5.1-0-dev
      - luarocks
      - uuid-dev
      - aspell
      - libopenmpi-dev
      - ccache

before_install:
  - export LD_LIBRARY_PATH=$HOME/local/lib
  - export CPPFLAGS=-I$HOME/local/include
  - export LDFLAGS=-L$HOME/local/lib
  - export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig
  - test "$TRAVIS_PULL_REQUEST" == "false" || export CCACHE_READONLY=1
  - if test "$CC" = "clang"; then export CCACHE_CPP2=1; fi
  - eval `luarocks path`
  - ./src/test/travis-dep-builder.sh --cachedir=$HOME/local/.cache
  - pip install --user cffi coverage

script:
 - export CC="ccache $CC"
 - ./autogen.sh
 - ./configure --prefix=$HOME/local
 - make -j2 distcheck

after_success:
 - ccache -s
